### ISSUE TITLE
GPG key has expired, install no longer possible

### ISSUE THREAD

**Issue by jmaris** [TingPing/transmission-remote-gnome#8]
The GPG key used to sign the flatpak has expired, install is no longer possible !

**Comment by TingPing** [comment]
I thought I renewed it but I don't know how that propagates to `flatpak`.

I pushed a new build, let me know if anything changes.

**Comment by jmaris** [comment]
Will try to install now :)

**Comment by jmaris** [comment]
The issue still occurs, i also believe the flatpak repo itsself may need updating (as i cannot get infromation regarding flatpaks in the repo

**Comment by jmaris** [comment]
```
[jmaris@homestead art]$ flatpak remote-add transmission "https://dl.tingping.se/flatpak/tingping.flatpakrepo"

[jmaris@homestead art]$ flatpak remote-ls transmission

error: GPG signatures found, but none are in trusted keyring

[jmaris@homestead art]$ 
```
